### PR TITLE
**Fix:** SectionHeader height

### LINKED ISSUE #1087: Fix SectionHeader height
There is [SectionHeader](https://github.com/contiamo/operational-ui/blob/master/src/Internals/SectionHeader.tsx) which uses

```
height: theme.space.element * 2,
```

This is wrong because we not suppose to use "space" (something around the content) for content size. 

Task is to change it to use `36px` from new design (do we need constant for it or we already have one?), as well find other occurrences of `theme.space.element * 2` and fix them.

PS SectionHeader is reused for Card headers, Tabs and Accordion

### PR DESCRIPTION
**Pull request by march213**
# Summary
Fixes #1087.
I changed all occurrences of `theme.space.element * 2` to `36px`.
Also in this file https://github.com/contiamo/operational-ui/blob/master/src/Tabs/Tabs.styled.ts#L23 I changed it to `56px` because the code was `height: ${({ theme }) => theme.space.element * 2 + 20}px` and remove the overwritten `height` property above.

# Related issue

https://github.com/contiamo/operational-ui/issues/1087

# To be tested

Me
- [x] No error or warning in the console on `localhost:6060`
- [x] Tabs component looks and works the same
- [x] Accordion component looks and works the same
- [x] HeaderBar component looks and works the same
- [x] Check other components that use HeaderMenu or SectionHeader

Tester 1

- [ ] Things look good on the demo.
  

Tester 2

- [ ] Things look good on the demo.

### CODE REVIEW

File: src/Internals/SectionHeader.tsx [hunk 1]
```diff
@@ -12,7 +12,7 @@ export const SectionHeader = styled("div")(({ theme }) => ({
 
   // This ensures that the card header text and card controls are placed in opposite corners.
   justifyContent: "space-between",
-  height: theme.space.element * 2,
+  height: "36px",
```
Comment (fabien0102) [inline src/Internals/SectionHeader.tsx]:
```suggestion
  height: 36,
```

You don't need to specify `px`, a number is enough here 😉

**Comment by TejasQ** [comment]
Wow! Great work, @march213!

I noticed an odd side effect as soon as I opened the [PR preview](https://deploy-preview-1092--operational-ui.netlify.com/) and clicked `diff with master`: `Card` titles are somehow smaller. 🤔 

Check it out: 
image

**Comment by stereobooster** [comment]
@TejasQ is it ok that we reuse 36 everywhere instead of introducing const? (And all of those 36 are the same thing height of header-like element)

**Comment by TejasQ** [comment]
Yeah @stereobooster it looks a little too wet (not DRY) for me too that it's concerning. Do you think it makes more sense to add it to the theme? I don't think it makes sense in the theme because it's not really something we want to be customizable, right? Maybe we can just export a `const`?

**Comment by stereobooster** [comment]
Const works as well. My may concern is that this value represent the same concept but from code it is hard to tell, because it's just a number 36

**Comment by TejasQ** [comment]
That's a great point. So then @march213, let's not add it to the theme but 

`export const headerHeight = 36`

from [here](https://github.com/contiamo/operational-ui/blob/64ff059da232c3eaa68b5efcceee6e0c741f3776/src/utils/constants.ts) and use it everywhere to convey the meaning behind the number.

Great observation, @stereobooster!

File: src/Internals/SectionHeader.tsx (hunk 1 above)
Comment (march213) [reply src/Internals/SectionHeader.tsx]: thanks! didn't notice that

**Comment by march213** [comment]
@TejasQ Done ✅

File: src/utils/constants.ts [hunk 2]
```diff
@@ -268,6 +268,8 @@ const constants = {
   },
 }
 
+export const headerHeight: number = 36
```
Comment (TejasQ) [inline src/utils/constants.ts]: We can remove the `: number` from here but not a big deal.

Comment (march213) [reply src/utils/constants.ts]: Yeah, actually I put it here, because in some places it should be a number ... But can remove it 🤔

Comment (TejasQ) [reply src/utils/constants.ts]: It's fine.

Comment (stereobooster) [reply src/utils/constants.ts]: TypeScript knows that `headerHeight` is a number without using signature in this case. They use so called [Type Inference](https://www.typescriptlang.org/docs/handbook/type-inference.html). Type checker can "guess" the type in this case, but it can't guess type in all cases, when it can't guess it will assign type `any` silently, unless there is `noImplicitAny` flag is enabled (it is in this repository). So you can skip all annotation and type checker will complain about those it can't guess. (As well sometime it guesses wrong, like `string` instead of string literal)

File: src/Tabs/Tabs.styled.ts [hunk 3]
```diff
@@ -1,26 +1,26 @@
...
 import { SectionHeader } from "../Internals/SectionHeader"
+import { headerHeight } from "../utils/constants"
 
 const buttonWidth = 55
 
 export const Container = styled.div`
   label: Tabs;
   display: grid;
-  grid-template-rows: ${({ theme }) => `${theme.space.element * 2}px 1fr`};
+  grid-template-rows: 36px 1fr;
```
Comment (stereobooster) [inline src/Tabs/Tabs.styled.ts]:
```suggestion
  grid-template-rows: ${headerHeight}px 1fr;
```

File: src/utils/constants.ts (hunk 2 above)
Comment (stereobooster) [inline src/utils/constants.ts]:
```suggestion
export const headerHeight = 36
```

**Comment by march213** [comment]
Should I make new PR ? I’ve made suggested changes

File: src/Tabs/Tabs.styled.ts (hunk 3 above)
Comment (march213) [reply src/Tabs/Tabs.styled.ts]: Ooops, my bad, sorry about that

Comment (TejasQ) [reply src/Tabs/Tabs.styled.ts]: Not a problem.

**Comment by TejasQ** [comment]
@stereobooster did the rest: https://github.com/contiamo/operational-ui/pull/1092

Thanks for your amazing work, @march213!
