### PR TITLE
**Fix:** Select menu not closing

### LINKED ISSUE #1056: Select/Context menu should close when  options is selected
[Select](http://operational-ui.netlify.com/#/Components/Select) with a single option should close when the selection is made. 

Select bug

### PR DESCRIPTION
**Pull request by mpotomin**
# Summary
Fixes #1056 – the regression, introduced  by https://github.com/contiamo/operational-ui/pull/1047
The context menu should close now as soon as an item within the menu is selected. It should still stay opened if `keepOpenOnItemClick` was provided

# Related issue
https://github.com/contiamo/operational-ui/issues/1056

# To be tested

Me
- [ ] No error or warning in the console on `localhost:6060`

Tester 1
- [ ] Context menu works as expected in all README.md cases (including multi-select cases)
- [ ] Select works as expected in all README.md cases (including multi-select functionalitfy)
- [ ] Action menu works as expected in all README.md cases

### CODE REVIEW

File: src/ContextMenu/ContextMenu.tsx [hunk 1]
```diff
@@ -217,10 +217,16 @@ const ContextMenu: React.FC<ContextMenuProps> = ({
...
                 if (!isString(item) && item.onClick) {
                   item.onClick(makeItem(item))
+                  if (!keepOpenOnItemClick && setIsOpen) {
+                    setIsOpen(false)
+                  }
                   return
                 }
                 if (onClick) {
                   onClick(makeItem(item))
+                  if (!keepOpenOnItemClick && setIsOpen) {
```
Comment (mpotomin) [inline src/ContextMenu/ContextMenu.tsx]: @TejasQ If i'm correct, this should close the menu since `e.stopPropagation()` was introduced at the top of this handler. 

Also would like to add a comment above the comment above `e.stopPropagation()` to explain why it is there. but i don't have enough context on it now.

File: src/ContextMenu/README.md [hunk 2]
```diff
@@ -123,7 +123,7 @@ import * as React from "react"
 import { ContextMenu, ContextMenuProps } from "@operational/components"
 
 const menuItems = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16].map(item => `Menu ${item}`)
-;<ContextMenu condensed items={menuItems} onClick={() => alert("clicked")}>
+;<ContextMenu keepOpenOnItemClick condensed items={menuItems} onClick={() => alert("clicked")}>
```
Comment (mpotomin) [inline src/ContextMenu/README.md]: @TejasQ I think `keepOpenOnItemClick` was is missing in the original doc and this example in the readme, otherwise i do not understand how this part is supposed to work, since the, unlike Select component, the is no `value` prop here to check if it is an array or not to figure if it should be multi-select, and all the examples receive an array of items. If so, `<div>Many options may be selected here</div>` is too ambiguous and should  something like "It will not close when the item is clicked"

**Comment by mpotomin** [comment]
@TejasQ This update fixes the behaviour for Select for both single-select and multi-select examples. I am not 100% sure that it is the case for the examples for the ActionMenu and ContextMenu, since the description in them is ambiguous. Please help test and improve them.

**Comment by fabien0102** [comment]
image

The focus is missing on focus (when you select the component with tab)

**Comment by fabien0102** [comment]
image

The state is not following when you remove the last caract

File: src/ContextMenu/README.md (hunk 2 above)
Comment (stereobooster) [reply src/ContextMenu/README.md]: I feel like this is escape hatch - we complicate API to make it work in all cases. Maybe this component tries to do to much things and we need to have to components or reconsider API/implementation?

File: src/ContextMenu/ContextMenu.tsx (hunk 1 above)
Comment (TejasQ) [reply src/ContextMenu/ContextMenu.tsx]: `e.stopPropagation` was introduced so that clicking on an item (which can have its own `onClick`) does not also trigger the parent's onClick, which can, in some cases, do more than just opening the menu.

I don't understand why you're doing this twice. You can check for this condition above both cases and handle open/close once?

File: src/ContextMenu/README.md (hunk 2 above)
Comment (TejasQ) [reply src/ContextMenu/README.md]: This example isn't really needed here, but on Select. I'm not sure what you're trying to do here?

**Comment by TejasQ** [comment]
Per @fabien0102's comments:

> The focus is missing on focus (when you select the component with tab)

There's an open issue for this: https://github.com/contiamo/operational-ui/issues/1006

> The state is not following when you remove the last caract

Let's open another issue for this and fix it separately. Let's not block this PR because it fixes a different problem.

File: src/ContextMenu/README.md (hunk 2 above)
Comment (mpotomin) [reply src/ContextMenu/README.md]: The example is saying "Many options may be selected here", which was not true - the menu was closing right after the first click on the item in it. Therefore I aded `keepOpenOnItemClick`, so that it at leas stays on the screen open after the first click so that any other item i selectable. 

Since you say, this example is not really needed here, lets remove it completely so it won't confuse someone else.

Comment (mpotomin) [reply src/ContextMenu/README.md]: Ah, now I see, "Many options may be selected here" means the list can be very long with *many* items in it. It does not mean that there can be multiple items selected when the context menu is opened. Updated the description.

File: src/ContextMenu/ContextMenu.tsx [hunk 3]
```diff
@@ -163,7 +163,7 @@ const ContextMenu: React.FC<ContextMenuProps> = ({
       {isOpen && (
         <InvisibleOverlay
           onClick={e => {
-            e.stopPropagation()
+            e.stopPropagation() //clicking on an item should not trigger the parent's onClick
```
Comment (TejasQ) [inline src/ContextMenu/ContextMenu.tsx]: That's not why this is here. In the context of this component, it has no parent – it is siblings with the menu.

It should read: clicking on this should trap clicks and not propagate them through parents – but this is kind of obvious with what `stopPropagation` does and I'm not sure it's needed here.
