### PR TITLE
**Fix:** Chip a11y

### LINKED ISSUE #990: `Chip`s update on hover even if unclickable
Currently, the background color of `Chip`s becomes darker when hovered – even if no click handler is present. I suggest we don't react to a cursor if a Chip is meant to be unresponsive.

### PR DESCRIPTION
**Pull request by TejasQ**
Fixes #990 and adds a11y superpowers to `Chip`.

lalala

### CODE REVIEW

File: src/Chip/Chip.tsx [hunk 1]
```diff
@@ -17,58 +18,90 @@ export interface ChipProps extends DefaultProps {
   children: React.ReactNode
 }
 
+const height = 20
```
Comment (fabien0102) [inline src/Chip/Chip.tsx]: Why? The theme value was not good enough for you? 🤔

Comment (TejasQ) [reply src/Chip/Chip.tsx]: theme.space for height is an anti-pattern
