### PR TITLE
**Fix** Tabs onActive callback called twice for each action

### LINKED ISSUE #1113: Tabs onActive callback called twice for each action
If you go to online playground https://operational-ui.netlify.com/#/Components/Tabs and change code like this:

```diff
- <Tabs tabs={tabs} active={active} onActivate={setActive} onClose={onClose} onInsert={onInsert}>
+ <Tabs tabs={tabs} active={active} onActivate={(x) => { console.log(`onActivate ${x}`); setActive(x);} } onClose={onClose} onInsert={onInsert}>
```

And then click any tab you will see it is called twice

image

### PR DESCRIPTION
**Pull request by kazionovm**
Remove onFocus prop in TabHeader component

# Summary
Fixes #1113

# Related issue
#1113

# To be tested

Me
- [ ] No error or warning in the console on `localhost:6060`

Tester 1

- [ ] Things look good on the demo.
- [ ] Paste this code and check if action calls once
```
<Tabs tabs={tabs} active={active} onActivate={(x) => { console.log(`onActivate ${x}`); setActive(x);} } onClose={onClose} onInsert={onInsert}>
```

Tester 2

- [ ] Things look good on the demo.
- [ ] Paste this code and check if action calls once
```
<Tabs tabs={tabs} active={active} onActivate={(x) => { console.log(`onActivate ${x}`); setActive(x);} } onClose={onClose} onInsert={onInsert}>
```

### CODE REVIEW

**Comment by TejasQ** [comment]
@kazionovm it appears your branch is out of sync with `master`. Please rebase.

**Comment by kazionovm** [comment]
@TejasQ and what to do next after rebase?

**Comment by stereobooster** [comment]
@kazionovm force push to your branch, it will update this PR, then all PR check will run and we can continue

**Comment by kazionovm** [comment]
@stereobooster okey, I'll fix it now

**Comment by TejasQ** [comment]
@kazionovm did you do it?

**Comment by kazionovm** [comment]
@TejasQ check now :)

**Comment by stereobooster** [comment]
@kazionovm not quite

Screenshot 2019-07-09 at 11 27 48

try something like this

```
git remote add upstream git@github.com:contiamo/operational-ui.git
git fetch upstream
git checkout tabs-fix
git rebase upstream/master
git push origin tabs-fix -f 
```

**Comment by kazionovm** [comment]
@stereobooster okey, I'll fix it

**Comment by TejasQ** [comment]
@kazionovm, please see https://github.com/contiamo/operational-ui/pull/789#issuecomment-434964942 for a little more info about this stuff if you're interested. Open to answer any questions you may have about it.

File: src/Tabs/Tabs.tsx [hunk 1]
```diff
@@ -171,16 +171,14 @@ const Tabs: React.FC<TabsProps> = ({
...
-              tabIndex={-1}
-              first={false}
-              aria-selected={false}
-              condensed={true}
-              onMouseDown={e => {
-                e.preventDefault()
-                userAction.current = true
-                onInsert(tabs.length - 1)
-              }}
+              tabIndex={i === active ? 0 : -1}
```
Comment (stereobooster) [inline src/Tabs/Tabs.tsx]: @kazionovm I think something went wrong with rebase. There was only one line of change and now there are more

**Comment by kazionovm** [comment]
@TejasQ  Done?

File: src/Tabs/Tabs.tsx (hunk 1 above)
Comment (kazionovm) [reply src/Tabs/Tabs.tsx]: @stereobooster Thank you!

File: src/Tabs/Tabs.tsx [hunk 2]
```diff
@@ -153,7 +153,6 @@ const Tabs: React.FC<TabsProps> = ({
                 id={`TabHeader-${uid}-${i}`}
                 key={i}
                 onClick={onClick}
-                onFocus={onClick}
```
Comment (stereobooster) [inline src/Tabs/Tabs.tsx]: So we don't use `onFocus`. It would be nice to remove it from `TabHeader` component

Comment (kazionovm) [reply src/Tabs/Tabs.tsx]: @stereobooster  I have done it

Comment (stereobooster) [reply src/Tabs/Tabs.tsx]: Ah `TabHeader` is just styled component, for some reason I thought it custom component. Ok. Then we need re-trigger tests and deployment preview which for some reason failed.
